-- Do not change the order of execution
DROP TABLE IF EXISTS Inventories;
DROP TABLE IF EXISTS OrderDetails;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Bookstores;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Branches;
DROP TABLE IF EXISTS Publishers;
DROP TABLE IF EXISTS HeadOffices;
DROP TABLE IF EXISTS Representatives;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS ReaderInterests;
