-- Do not change the order of execution
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS OrderDetails;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Bookstore;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Branch;
DROP TABLE IF EXISTS Publisher;
DROP TABLE IF EXISTS HeadOffice;
DROP TABLE IF EXISTS Representative;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS ReaderInterest;
